import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Box } from '@chakra-ui/react'
import { Navbar } from '@/components/navbar/navbar'
import { Sidebar } from '@/components/sidebar/sidebar'
import { Provider } from '@/components/ui/provider'
import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'WatchMe',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  }
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} m-auto bg-background text-gray-100 overflow-hidden`}>
        <Provider>
          <Navbar />
          <Box as="div" display="flex" width="full" height="full">
            <Sidebar />
            <Box
              as="div"
              display="flex"
              flexDirection="column"
              width="full"
              padding="4"
              className="bg-gray-900 p-6">
              {children}
            </Box>
          </Box>
        </Provider>
      </body>
    </html>
  )
}
