import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'
import { Provider } from '@/components/ui/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'WatchMe',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png'
  }
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} m-auto bg-gray-900 text-gray-100 overflow-hidden`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
