root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -C ./cmd/watchMe -o ../../tmp/main.exe"
  bin = "./tmp/main"
  delay = 1000 # ms
  exclude_dir = ["assets", "tmp", "vendor", "_postgres"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]
  include_file = [".env"]

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true