services:
  db:
    image: postgres:14.3
    container_name: watchme-db
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./_postgres:/var/lib/postgresql/data
  redis:
    container_name: watchme-redis
    restart: always
    image: redis:8.2.1-alpine
    ports:
      - ${REDIS_PORT}:6379
    volumes: 
      - ./_redis:/data
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD} --protected-mode yes
    depends_on:
      - db
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - REDIS_PASSWORD=${REDIS_PASSWORD}
    - REDIS_USERNAME=${REDIS_USERNAME}
    depends_on:
      - redis
    ports:
    - "8081:8081"
