basePath: /api
info:
  contact: {}
  description: This is the API documentation for the WatchMe application.
  title: WatchMe API
  version: "1.0"
paths:
  /auth/github:
    get:
      description: OAuth2 login with Github
      responses: {}
      tags:
      - Auth
  /auth/github/callback:
    get:
      responses: {}
      tags:
      - Auth
  /auth/logout:
    post:
      responses: {}
      tags:
      - Auth
  /streamer/:username:
    get:
      description: Get the streamer's information
      parameters:
      - description: Username of the user
        in: path
        name: username
        required: true
        type: string
      responses: {}
      tags:
      - Streamer
  /streamer/search/:username:
    get:
      description: Get the streamer's information
      parameters:
      - description: Username of the user
        in: path
        name: username
        required: true
        type: string
      responses: {}
      tags:
      - Streamer
  /streams/:username:
    get:
      description: Get the live stream for the user
      parameters:
      - description: Username of the user
        in: path
        name: username
        required: true
        type: string
      responses: {}
      tags:
      - Streams
  /streams/delete-key/:streamKeyId:
    delete:
      description: Delete a stream key for a live stream
      parameters:
      - description: Stream key id
        in: path
        name: streamKeyId
        required: true
        type: string
      responses: {}
      tags:
      - Streams
  /streams/delete-stream/:playbackId:
    delete:
      description: Delete the stream from the database
      parameters:
      - description: Playback ID of the stream
        in: path
        name: playbackId
        required: true
        type: string
      responses: {}
      tags:
      - Streams
  /streams/edit-stream/:playbackId:
    patch:
      description: Edit the title of a live stream
      parameters:
      - description: Playback ID of the stream
        in: path
        name: playbackId
        required: true
        type: string
      responses: {}
      tags:
      - Streams
  /streams/feed:
    get:
      description: Get the feed for the home page
      responses: {}
      tags:
      - Streams
  /streams/generate-key:
    get:
      description: Generate a stream key for a live stream
      responses: {}
      tags:
      - Streams
  /users:
    get:
      description: Get the user's information
      responses: {}
      tags:
      - Users
    patch:
      description: Update a user's information
      responses: {}
      tags:
      - Users
  /users/follow/:username:
    post:
      description: Follow a user
      parameters:
      - description: Username of the user to follow
        in: path
        name: username
        required: true
        type: string
      responses: {}
      tags:
      - Users
  /users/unfollow/:username:
    post:
      description: Unfollow a user
      parameters:
      - description: Username of the user to unfollow
        in: path
        name: username
        required: true
        type: string
      responses: {}
      tags:
      - Users
swagger: "2.0"
